spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.ld5naek.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for user management'
    version: '1.0.0'